#!/data/data/com.termux/files/usr/bin/env python3
"""
GRANT READY SUMMARY GENERATOR
Reads MASTER_CONTEXT_ANCHOR_v2.txt and extracts key metrics for funding applications.
Uses the 'cat ... EOF' method to ensure safe execution.
"""

import os
import re
from datetime import datetime

# CONFIGURATION
PROJECT_ROOT = os.path.expanduser("~/AERO_ROOT")
CONTEXT_FILE = os.path.join(PROJECT_ROOT, "99-INBOX", "downloads", "MASTER_CONTEXT_ANCHOR_v2.txt")
OUTPUT_FILE = os.path.join(PROJECT_ROOT, "01-ADMIN", "GRANT_SUMMARY_$(date +%Y%m%d).txt")

def extract_key_metric(content, metric_name):
    """Simple regex extractor for specific claims."""
    # Look for patterns like "PTTR > 9,000:1" or "9000:1"
    pattern = rf"{metric_name}.*?(\d+:\d+|\d+:\d+:\d+)"
    match = re.search(pattern, content, re.IGNORECASE | re.DOTALL)
    return match.group(1) if match else "Not Found"

def main():
    print("📄 Generating Grant Summary...")
    
    # Check if file exists
    if not os.path.exists(CONTEXT_FILE):
        print(f"❌ Error: Could not find {CONTEXT_FILE}")
        print("   Make sure MASTER_CONTEXT_ANCHOR_v2.txt is in 99-INBOX/downloads")
        return

    # Read File
    with open(CONTEXT_FILE, 'r', encoding='utf-8') as f:
        content = f.read()

    # Extract Critical Data
    pttr = extract_key_metric(content, "PTTR")
    copyright = extract_key_metric(content, "Open Source") # Simplified check
    mission = "Trash to Treasure / Decentralized Energy"
    
    # Format Date
    today = datetime.now().strftime("%Y-%m-%d")
    out_path = os.path.join(PROJECT_ROOT, "01-ADMIN", f"GRANT_SUMMARY_{today}.txt")

    # Generate Report
    report = f"""
================================================================================
          GRANT APPLICATION SUMMARY: AEROCENT ECOSYSTEM
          Generated: {today}
================================================================================
PRINCIPAL INVESTIGATOR: Jesse McMillen
PROJECT TITLE: Passive Solar Loop & Open-Cell Aerocement

1. CORE METRICS (From Master Context)
   - Efficiency Ratio (PTTR): {pttr}
   - Mission Philosophy: {mission}
   - Licensing Strategy: Open Source (CC-BY-SA Hardware / GPL Software)

2. KEY CLAIMS FOR FUNDING
   - Validates physics of buoyancy-driven thermal loops.
   - Utilizes waste streams (cardboard, chemical byproducts) for shelter.
   - Provides grid-independent energy and food production.

3. CURRENT STATUS
   - Physics Validated: Yes
   - Prototype Stage: Pre-prototype (Bench scale pending)
   - Patent Status: Pending Provisional Filing

4. REQUESTED SUPPORT
   - Funding for bench prototype materials ($5k - $20k).
   - Technical validation support (sensor instrumentation).
   - Land acquisition for field deployment.

================================================================================
Generated by Lumo (General Advisor) via Termux Automation
================================================================================
"""

    # Save Report
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(report)

    print(f"✅ Summary Generated Successfully!")
    print(f"   Location: {out_path}")
    print(f"\n--- PREVIEW ---")
    print(report[:500] + "...") # Show first 500 chars

if __name__ == "__main__":
    main()
